name = "hono-stripe"
compatibility_date = "2024-08-01"
account_id = "ea51b75169de83e45a4cec802beb942d"
workers_dev = true
node_compat = true

main = "./src/index.ts"

[vars]
DATABASE_URL = "mongodb://localhost:27017/hono"
STRIPE_SECRET_KEY = "sk_test_51Pj5vrKnmkTtnse15vvE0RPGoipfEjdQcENXaL2Ak4meOd5CrbO7olyA306ZI0p5Dr1gOa4YpC9VC16FXc4iIn3U008icJlhEo"
RANDVAR="Hello Var 😀"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
